apiVersion: v1
kind: Service
metadata:
  name: serverapp-svc # Nombre del servicio.
spec:
  selector:
    app: serverapp # Apunta a los pods que tengan esta etiqueta.
  ports:
    - protocol: TCP
      port: 5000 #puerto expuesto en el servicio.
      targetPort: 5000 #puerto en los pods a los que el tráfico del servicio será dirigido.