name: deploy-eks

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        run: |
          nvm install 16
          nvm use 16

      - name: Checkout repo
        uses: actions/checkout@v2.4.3

      - name: Configurar Kubeconfig
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig.yaml
          kubectl config use-context mi-contexto
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Despliegue a Kubernetes
        run: |
          kubectl apply -f deployment.yaml
        env:
          KUBECONFIG: ./kubeconfig.yaml
