name: Kubernetes Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
          version: latest

      - name: Despliegue a Kubernetes
        run: |
          kubectl apply -f manifiestos/deployment.yaml --server=http://http://127.0.0.1:39937
        env:
          KUBECONFIG: ./kubeconfig.yaml

